[dependencies]
base = "0.8.1"
itertools = "0.1.1"
serde = "0.2.0"
http = "https://github.com/aviate-labs/http.mo#v0.1.1"
json = "https://github.com/aviate-labs/json.mo#v0.2.0"
moh = "https://github.com/NatLabs/moh#main"
parser-combinators = "https://github.com/aviate-labs/parser-combinators.mo#v0.1.3"
"encoding-v0.4.1" = "https://github.com/aviate-labs/encoding.mo#v0.4.1"

[package]
name = "web-api"
version = "0.1.0"
description = ""
repository = ""

[dev-dependencies]
test = "1.0.1"