[dependencies]
base = "0.8.1"
itertools = "0.1.2"
serde = "1.0.2"
http = "https://github.com/aviate-labs/http.mo#v0.1.1"
moh = "https://github.com/NatLabs/moh#main"
parser-combinators = "https://github.com/aviate-labs/parser-combinators.mo#v0.1.3"
encoding = "https://github.com/aviate-labs/encoding.mo#v0.4.1"
fuzz = "0.1.0"

[package]
name = "web-io"
version = "0.0.1"
description = "A set of modules for creating http requests and handling responses"
repository = "https://github.com/NatLabs/web-io"
keywords = ["http", "web"]

[dev-dependencies]
test = "1.0.1"